GET http://localhost:8080/create_thread
Content-Type: application/json

{
    "category": "food",
    "theme": "dinner",
    "description": "Who want to eat?",
    "options": ["a", "b", "c"]
}
###

GET http://localhost:8080/get_thread
Content-Type: application/json

{
    "thread_id": "thread1652543185077"
}
###

GET http://localhost:8080/create_vote
Content-Type: application/json

{
    "thread_id": "thread1652543185077"
}
###

GET http://localhost:8080/use_vote
Content-Type: application/json

{
    "thread_id": "thread1652543185077",
    "vote_id": "42dffdf18263cd97897290a2cc2f70545627c19a76e1258a9162b0584ec3e50d",
    "option": "a"
}
###

GET http://localhost:8080/end_thread
Content-Type: application/json

{
    "thread_id": "thread1652543185077"
}